TRAIN:
  ENABLE: True
  DATASET: aicity
  BATCH_SIZE: 3
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 40
  CHECKPOINT_FILE_PATH: data/ckpts/MViTv2_S_16x4_pretrained.pyth
  AUTO_RESUME: False
  CHECKPOINT_EPOCH_RESET: True
  MIXED_PRECISION: False
DATA:
  DECODING_BACKEND: decord
  NUM_FRAMES: 16
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [ 480, 540 ]
  TRAIN_CROP_SIZE: 448
  TEST_CROP_SIZE: 448
  INPUT_CHANNEL_NUM: [ 3 ]
  TRAIN_JITTER_SCALES_RELATIVE: [ 0.08, 1.0 ]
  TRAIN_JITTER_ASPECT_RELATIVE: [ 0.75, 1.3333 ]
  RANDOM_FLIP: False
  PATH_PREFIX: data/preprocessed/A1_clips
  PATH_TO_DATA_DIR: data/annotations/splits/full
MVIT:
  ZERO_DECAY_POS_CLS: False
  SEP_POS_EMBED: True
  DEPTH: 16
  NUM_HEADS: 1
  EMBED_DIM: 96
  PATCH_KERNEL: (3, 7, 7)
  PATCH_STRIDE: (2, 4, 4)
  PATCH_PADDING: (1, 3, 3)
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPPATH_RATE: 0.4   # 0.4 for ssv2
  NORM: "layernorm"
  MODE: "conv"
  CLS_EMBED_ON: False
  DIM_MUL: [ [ 1, 2.0 ], [ 3, 2.0 ], [ 14, 2.0 ] ]
  HEAD_MUL: [ [ 1, 2.0 ], [ 3, 2.0 ], [ 14, 2.0 ] ]
  POOL_KVQ_KERNEL: [ 3, 3, 3 ]
  POOL_KV_STRIDE_ADAPTIVE: [ 1, 8, 8 ]
  POOL_Q_STRIDE: [ [ 1, 1, 2, 2 ], [ 3, 1, 2, 2 ], [ 14, 1, 2, 2 ] ]
  DROPOUT_RATE: 0.0
  CHANNEL_EXPAND_FRONT: True
  Q_POOL_ALL: True
  Q_POOL_RESIDUAL: True
AUG:
  ENABLE: False
MIXUP:
  ENABLE: False
  ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  PROB: 1.0
  SWITCH_PROB: 0.5
  LABEL_SMOOTH_VALUE: 0.1
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  ZERO_WD_1D_PARAM: True
  CLIP_GRAD_L2NORM: 1.0
  BASE_LR_SCALE_NUM_SHARDS: False
  BASE_LR: 5e-6
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-7
  WARMUP_START_LR: 1e-7
  WARMUP_EPOCHS: 30.0
  LR_POLICY: cosine
  MAX_EPOCH: 200
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: adamw
MODEL:
  NUM_CLASSES: 16
  ARCH: mvit
  MODEL_NAME: MViT
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
  ACT_CHECKPOINT: True
TEST:
  ENABLE: False
  DATASET: aicity
  BATCH_SIZE: 5
  NUM_SPATIAL_CROPS: 1
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
LOG_PERIOD: 1000
USE_TQDM: True
LOG_MODEL_INFO: False
TENSORBOARD:
  ENABLE: True
  LOG_DIR: tb_log